name: hs-party
version: 0.1.0.0
github: "isyuck/hs-party"
license: BSD3
author: "isaac spicer"
copyright: "2021 isaac spicer"

extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - hosc
  - network
  - mtl
  - text
  - websockets
  - wuss

library:
  source-dirs: src

executables:
  hs-party-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hs-party
